# Site settings
title: Understanding DORA Delivery Metrics
domain: dora-delivery.dev       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://dora-delivery.dev/  # the base hostname and protocol for your site, e.g. http://example.com

# Build settings
plugins:
  - jekyll-sitemap
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-relative-links
  - jekyll-remote-theme

theme: minima

readme_index:
  enabled:          true
  remove_originals: true
  with_frontmatter: false
